### ISSUE TITLE
Add MUMPS

### ISSUE THREAD

**Issue by garth-wells** [conda-forge/petsc-feedstock#12]
Adding MUMPS would provide a parallel direct solver. 

MUMPS is packaged at https://github.com/conda-forge/mumps-feedstock, but will probably need some work. The MUMPS conda package depends on scotch rather than pt-scotch, which may mean that it won't work in parallel.

There is also an issue with scalpack to sort out.

**Comment by dalcinl** [comment]
OK, then here goes my proposal: If the `mumps` package is not built with MPI as we need, then we create our own `mumps-mpi` package, make it use `pt-scotch` (and create that package as well if required), and also `parmetis`, and I guess the issue with `scalapack` is that there is no package yet, right? so have another one to create... All of them should be built for both MPICH and Open MPI. Yes, this is quite a bit of work, but it will pay off in the long run.

**Comment by garth-wells** [comment]
I would forget ParMETIS (for the time being, and maybe forever). It is not available under an open source license (see http://glaros.dtc.umn.edu/gkhome/metis/parmetis/download).

pt-scotch is available (as a branch under the scotch feedstock, https://github.com/conda-forge/scotch-feedstock/tree/ptscotch).

**Comment by minrk** [comment]
I started scalapack [here](https://github.com/conda-forge/staged-recipes/pull/2609), and asked about where folks would like to put parallel mumps [here](https://github.com/conda-forge/mumps-feedstock/issues/14).
