### ISSUE TITLE
petsc4py version mismatch

### ISSUE THREAD

**Issue by caidao22** [conda-forge/petsc-feedstock#141]
### Comment:

The current petsc4py version does not match the petsc version. 
```
petsc                     3.17.1          real_h6e9d0b6_100    conda-forge
petsc4py                  3.17.0          real_h016f20b_100    conda-forge
```

Btw, I am wondering if there is any way to install a single-precision build of petsc4py through conda. Thanks!

**Comment by dalcinl** [comment]
> The current petsc4py version does not match the petsc version.

That's because I forgot to upload the release tarballs to PyPI. I just did. The bot will eventually issue the update PR.

> Btw, I am wondering if there is any way to install a single-precision build of petsc4py through conda

We do not have single precision variants yet. We have real vs complex, but not single vs double.

**Comment by minrk** [comment]
both are on 3.17.2 now
