### ISSUE TITLE
petsc with hypre and ml

### ISSUE THREAD

**Issue by xmjiao** [conda-forge/petsc-feedstock#15]
It seems that HYPRe and ML are not supported in PETSc for the `conda-forge` build. It is unfortunate that we cannot use these preconditioners (especially BoomerAMG in HYPRe) with PETSc because HYPRe's AMG implementation is the best for many problems we tested. 

Is there a plan to build with them (at least HYPRE) for conda-forge? I know that there are no feedstocks for `hypre` and `ml` on `conda-forge` yet, and `--download-hypre` and `--download-ml` are not allowed during the building process. Maybe HYPRe and ML's source codes can be directly included in the PETSc source tree? Thanks!

**Comment by minrk** [comment]
I'll investigate making hypre and ml recipes, then we should be able to include them as regular dependencies.

**Comment by MarDiehl** [comment]
I am maintaining PETSc for Arch Linux (https://aur.archlinux.org/packages/petsc/) and ML/Trilinos is by far the most annoying dependency. It fails often (for example because the link command is too long if not build in /tmp) and building takes ages.
