### ISSUE TITLE
petsc.mod missing when wrapping fortran around petsc4py

### ISSUE THREAD

**Issue by apatlpo** [conda-forge/petsc-feedstock#24]
I am trying to wrap fortran code around petsc4py and encountered the issue described at:
https://lists.mcs.anl.gov/pipermail/petsc-users/2018-January/034261.html

It appears the conda install of petsc does not come with petsc.mod files.

Is it intended?

**Comment by dalcinl** [comment]
Yes, it is intended, we explicitly configure with `--with-fc=0`.  However, given that now both MPICH and Open MPI are built with Fortran support, I think it is time to revisit that choice.

**Comment by apatlpo** [comment]
ok, thanks, would you have a timeline on when you'll have time to look at this?

**Comment by dalcinl** [comment]
I'm working on it.

**Comment by dalcinl** [comment]
@apatlpo This is taking longer than expected, the Travis-CI infrastructure in charge of testing macOS builds had some recent issues and builds are still in the queue. After merging #25, you will have to wait for another round of builds to get the binary packages uploaded to anaconda.org.

**Comment by dalcinl** [comment]
@apatlpo Fresh packages are now available in anaconda.org/conda-forge/petsc. I'm closing this issue. In case of trouble, please drop me a comment mentioning me.
