### ISSUE TITLE
Adding HDF5 and FFTW support

### ISSUE THREAD

**Issue by MarDiehl** [conda-forge/petsc-feedstock#57]
PETSc supports HDF5 and FFTW. Both packages are available on conda, so it should be possible to add them. This makes buidling/linking applications easier because the PETSc commands will include -lfftw3, -lhdf5 etc. The drawback is of course the dependency on these packages

**Comment by Fvergnet** [comment]
Do you have some news on this issue ? Is it now possible to install petsc with hdf5 in a conda environment ? Otherwise, how can I use hdf5 within petsc in a conda environment ?

**Comment by MarDiehl** [comment]
is implemented
